// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRh55a76WiDj0GLTItodqL1NtqWSWjUAs',
    appId: '1:12338857799:web:93fb6fe8103061fe236e62',
    messagingSenderId: '12338857799',
    projectId: 'stuff-app-9000',
    authDomain: 'stuff-app-9000.firebaseapp.com',
    storageBucket: 'stuff-app-9000.firebasestorage.app',
    measurementId: 'G-SCPZXELDRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCjJiRmIADc1YU3VLcHDbXOfquJDufW5M',
    appId: '1:12338857799:android:cf820030d5e58037236e62',
    messagingSenderId: '12338857799',
    projectId: 'stuff-app-9000',
    storageBucket: 'stuff-app-9000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1gZKHtok6QZM03fumAIF7RYAnAcEoj0',
    appId: '1:12338857799:ios:6f8aed19d2394e6d236e62',
    messagingSenderId: '12338857799',
    projectId: 'stuff-app-9000',
    storageBucket: 'stuff-app-9000.firebasestorage.app',
    iosBundleId: 'com.example.stuffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1gZKHtok6QZM03fumAIF7RYAnAcEoj0',
    appId: '1:12338857799:ios:6f8aed19d2394e6d236e62',
    messagingSenderId: '12338857799',
    projectId: 'stuff-app-9000',
    storageBucket: 'stuff-app-9000.firebasestorage.app',
    iosBundleId: 'com.example.stuffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRh55a76WiDj0GLTItodqL1NtqWSWjUAs',
    appId: '1:12338857799:web:78430053d9c33694236e62',
    messagingSenderId: '12338857799',
    projectId: 'stuff-app-9000',
    authDomain: 'stuff-app-9000.firebaseapp.com',
    storageBucket: 'stuff-app-9000.firebasestorage.app',
    measurementId: 'G-GCFKVG3GC2',
  );

}